### ISSUE TITLE
lintrunner flake 8 failure

### ISSUE THREAD

**Issue by H-Huang** [suo/lintrunner#13]
Thanks for this tool @suo! It has been super helpful. I am hitting two issues:

# Issue 1

For this PR (https://github.com/pytorch/pytorch/pull/83735) the linter failed to run but still printed out "Successfully applied all patches." Do you know how I can fix the flake8 issue?

Command:
`lintrunner -a`

Output:
```
...
>>> General linter failure:

  Error (FLAKE8) command-failed
    COMMAND (exit code 1)
    /private/home/howardhuang/.conda/envs/pytorch/bin/python3 -mflake8 --exit-
    zero /private/home/howardhuang/pytorch-projects/pytorch/test/distributed/
    test_c10d_common.py
    
    STDERR
    Traceback (most recent call last):
      File "/private/home/howardhuang/.conda/envs/pytorch/lib/python3.8/site-
    packages/flake8/plugins/manager.py", line 157, in load_plugin
        self._load()
      File "/private/home/howardhuang/.conda/envs/pytorch/lib/python3.8/site-
    packages/flake8/plugins/manager.py", line 134, in _load
        self._plugin = self.entry_point.load()
      File "/private/home/howardhuang/.conda/envs/pytorch/lib/python3.8/
    importlib/metadata.py", line 77, in load
        module = import_module(match.group('module'))
      File "/private/home/howardhuang/.conda/envs/pytorch/lib/python3.8/
    importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in
    _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in
    _call_with_frames_removed
      File "/private/home/howardhuang/.conda/envs/pytorch/lib/python3.8/site-
    packages/pyi.py", line 12, in <module>
        from pyflakes.checker import PY2, ClassDefinition
    ImportError: cannot import name 'PY2' from 'pyflakes.checker' (/private/
    home/howardhuang/.local/lib/python3.8/site-packages/pyflakes/checker.py)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/home/howardhuang/.conda/envs/pytorch/lib/python3.8/
    runpy.py", line 194, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/private/home/howardhuang/.conda/envs/pytorch/lib/python3.8/
    runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/private/home/howardhuang/.conda/envs/pytorch/lib/python3.8/site-
    packages/flake8/__main__.py", line 4, in <module>
        cli.main()
      File "/private/home/howardhuang/.conda/envs/pytorch/lib/python3.8/site-
    packages/flake8/main/cli.py", line 22, in main
        app.run(argv)
      File "/private/home/howardhuang/.conda/envs/pytorch/lib/python3.8/site-
    packages/flake8/main/application.py", line 360, in run
        self._run(argv)
      File "/private/home/howardhuang/.conda/envs/pytorch/lib/python3.8/site-
    packages/flake8/main/application.py", line 347, in _run
        self.initialize(argv)
      File "/private/home/howardhuang/.conda/envs/pytorch/lib/python3.8/site-
    packages/flake8/main/application.py", line 328, in initialize
        self.find_plugins(config_finder)
      File "/private/home/howardhuang/.conda/envs/pytorch/lib/python3.8/site-
    packages/flake8/main/application.py", line 159, in find_plugins
        self.check_plugins.load_plugins()
      File "/private/home/howardhuang/.conda/envs/pytorch/lib/python3.8/site-
    packages/flake8/plugins/manager.py", line 415, in load_plugins
        plugins = list(self.manager.map(load_plugin))
      File "/private/home/howardhuang/.conda/envs/pytorch/lib/python3.8/site-
    packages/flake8/plugins/manager.py", line 302, in map
        yield func(self.plugins[name], *args, **kwargs)
      File "/private/home/howardhuang/.conda/envs/pytorch/lib/python3.8/site-
    packages/flake8/plugins/manager.py", line 413, in load_plugin
        return plugin.load_plugin()
      File "/private/home/howardhuang/.conda/envs/pytorch/lib/python3.8/site-
    packages/flake8/plugins/manager.py", line 164, in load_plugin
        raise failed_to_load
    flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "Y0"
    due to cannot import name 'PY2' from 'pyflakes.checker' (/private/home/
    howardhuang/.local/lib/python3.8/site-packages/pyflakes/checker.py).
    
    STDOUT
    (empty)
Successfully applied all patches.
```

# Issue 2

Command
```
lintrunner rage
```

output:
```
error:        No such file or directory (os error 2)
```

**Comment by H-Huang** [comment]
NVM, i just uninstalled and reinstalled lintrunner and everything is fine now. Not sure how it got into that previous state.

**Comment by suo** [comment]
weird, feel free to reopen if you're seeing it again :)
